# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matt/Documents/GitHub/VmEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matt/Documents/GitHub/VmEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matt/Documents/GitHub/VmEngine/CMakeFiles /home/matt/Documents/GitHub/VmEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matt/Documents/GitHub/VmEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named v0idengine

# Build rule for target.
v0idengine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v0idengine
.PHONY : v0idengine

# fast build rule for target.
v0idengine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/build
.PHONY : v0idengine/fast

src/Bitmask.o: src/Bitmask.cpp.o

.PHONY : src/Bitmask.o

# target to build an object file
src/Bitmask.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Bitmask.cpp.o
.PHONY : src/Bitmask.cpp.o

src/Bitmask.i: src/Bitmask.cpp.i

.PHONY : src/Bitmask.i

# target to preprocess a source file
src/Bitmask.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Bitmask.cpp.i
.PHONY : src/Bitmask.cpp.i

src/Bitmask.s: src/Bitmask.cpp.s

.PHONY : src/Bitmask.s

# target to generate assembly for a file
src/Bitmask.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Bitmask.cpp.s
.PHONY : src/Bitmask.cpp.s

src/Input.o: src/Input.cpp.o

.PHONY : src/Input.o

# target to build an object file
src/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Input.cpp.o
.PHONY : src/Input.cpp.o

src/Input.i: src/Input.cpp.i

.PHONY : src/Input.i

# target to preprocess a source file
src/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Input.cpp.i
.PHONY : src/Input.cpp.i

src/Input.s: src/Input.cpp.s

.PHONY : src/Input.s

# target to generate assembly for a file
src/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Input.cpp.s
.PHONY : src/Input.cpp.s

src/KeyboardMovement.o: src/KeyboardMovement.cpp.o

.PHONY : src/KeyboardMovement.o

# target to build an object file
src/KeyboardMovement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/KeyboardMovement.cpp.o
.PHONY : src/KeyboardMovement.cpp.o

src/KeyboardMovement.i: src/KeyboardMovement.cpp.i

.PHONY : src/KeyboardMovement.i

# target to preprocess a source file
src/KeyboardMovement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/KeyboardMovement.cpp.i
.PHONY : src/KeyboardMovement.cpp.i

src/KeyboardMovement.s: src/KeyboardMovement.cpp.s

.PHONY : src/KeyboardMovement.s

# target to generate assembly for a file
src/KeyboardMovement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/KeyboardMovement.cpp.s
.PHONY : src/KeyboardMovement.cpp.s

src/Object.o: src/Object.cpp.o

.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i

.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s

.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/ResourcePath.o: src/ResourcePath.cpp.o

.PHONY : src/ResourcePath.o

# target to build an object file
src/ResourcePath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/ResourcePath.cpp.o
.PHONY : src/ResourcePath.cpp.o

src/ResourcePath.i: src/ResourcePath.cpp.i

.PHONY : src/ResourcePath.i

# target to preprocess a source file
src/ResourcePath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/ResourcePath.cpp.i
.PHONY : src/ResourcePath.cpp.i

src/ResourcePath.s: src/ResourcePath.cpp.s

.PHONY : src/ResourcePath.s

# target to generate assembly for a file
src/ResourcePath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/ResourcePath.cpp.s
.PHONY : src/ResourcePath.cpp.s

src/SceneStateMachine.o: src/SceneStateMachine.cpp.o

.PHONY : src/SceneStateMachine.o

# target to build an object file
src/SceneStateMachine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/SceneStateMachine.cpp.o
.PHONY : src/SceneStateMachine.cpp.o

src/SceneStateMachine.i: src/SceneStateMachine.cpp.i

.PHONY : src/SceneStateMachine.i

# target to preprocess a source file
src/SceneStateMachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/SceneStateMachine.cpp.i
.PHONY : src/SceneStateMachine.cpp.i

src/SceneStateMachine.s: src/SceneStateMachine.cpp.s

.PHONY : src/SceneStateMachine.s

# target to generate assembly for a file
src/SceneStateMachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/SceneStateMachine.cpp.s
.PHONY : src/SceneStateMachine.cpp.s

src/Sprite.o: src/Sprite.cpp.o

.PHONY : src/Sprite.o

# target to build an object file
src/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Sprite.cpp.o
.PHONY : src/Sprite.cpp.o

src/Sprite.i: src/Sprite.cpp.i

.PHONY : src/Sprite.i

# target to preprocess a source file
src/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Sprite.cpp.i
.PHONY : src/Sprite.cpp.i

src/Sprite.s: src/Sprite.cpp.s

.PHONY : src/Sprite.s

# target to generate assembly for a file
src/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Sprite.cpp.s
.PHONY : src/Sprite.cpp.s

src/Transform.o: src/Transform.cpp.o

.PHONY : src/Transform.o

# target to build an object file
src/Transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Transform.cpp.o
.PHONY : src/Transform.cpp.o

src/Transform.i: src/Transform.cpp.i

.PHONY : src/Transform.i

# target to preprocess a source file
src/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Transform.cpp.i
.PHONY : src/Transform.cpp.i

src/Transform.s: src/Transform.cpp.s

.PHONY : src/Transform.s

# target to generate assembly for a file
src/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Transform.cpp.s
.PHONY : src/Transform.cpp.s

src/Window.o: src/Window.cpp.o

.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i

.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s

.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v0idengine.dir/build.make CMakeFiles/v0idengine.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... v0idengine"
	@echo "... src/Bitmask.o"
	@echo "... src/Bitmask.i"
	@echo "... src/Bitmask.s"
	@echo "... src/Input.o"
	@echo "... src/Input.i"
	@echo "... src/Input.s"
	@echo "... src/KeyboardMovement.o"
	@echo "... src/KeyboardMovement.i"
	@echo "... src/KeyboardMovement.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/ResourcePath.o"
	@echo "... src/ResourcePath.i"
	@echo "... src/ResourcePath.s"
	@echo "... src/SceneStateMachine.o"
	@echo "... src/SceneStateMachine.i"
	@echo "... src/SceneStateMachine.s"
	@echo "... src/Sprite.o"
	@echo "... src/Sprite.i"
	@echo "... src/Sprite.s"
	@echo "... src/Transform.o"
	@echo "... src/Transform.i"
	@echo "... src/Transform.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

